### ISSUE TITLE
feat/Enum 클래스 생성

### ISSUE THREAD

**Issue by yarogono** [Hwan007/TextRPGing#4]
# Enum 클래스 생성

- eSceneType
  - Status = 0
  - Battle = 1
  - Recovery = 2
  - SaveLoad = 3
- eItemType
  - Potion = 0
  - Amor = 1
  - Weapon = 2
- eSkillType
  - Potion = 0
  - Amor = 1
  - Weapon

**Comment by Hwan007** [comment]
👍
